# Generated by Django 4.2.13 on 2025-08-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authorapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorapplication',
            name='sample_of_work',
            field=models.FileField(default=1, upload_to='author_samples/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authorapplication',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
