# Generated by Django 4.2.13 on 2025-08-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_authorapplication_sample_of_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorapplication',
            name='sample_of_work',
            field=models.FileField(blank=True, null=True, upload_to='author_samples/'),
        ),
    ]
