# Generated by Django 4.2.13 on 2025-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_authorapplication_status_follow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorapplication',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('approved', 'Approved'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
    ]
