# Generated by Django 4.2.13 on 2025-09-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_subscribe_alter_authorapplication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorapplication',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
