# Generated by Django 4.2.13 on 2025-09-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_authorapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorapplication',
            name='status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=10),
        ),
    ]
