# Generated by Django 4.2.13 on 2025-09-16 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_authorapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorapplication',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
