# Generated by Django 4.2.13 on 2025-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the genre.', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='A URL-friendly version of the genre name.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the genre.')),
            ],
            options={
                'verbose_name_plural': 'genres',
                'ordering': ['name'],
            },
        ),
    ]
