# Generated by Django 4.2.13 on 2025-08-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-published_date']},
        ),
        migrations.AddField(
            model_name='story',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='The genres for this story.', related_name='stories', to='books.genre'),
        ),
    ]
