# Generated by Django 4.2.13 on 2025-08-28 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_story_options_story_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['story', 'chapter_number']},
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='order',
            new_name='chapter_number',
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('story', 'chapter_number')},
        ),
    ]
