# Generated by Django 4.2.13 on 2025-09-16 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_readingprogress_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='readingprogress',
            name='unique_progress_per_user_story',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='char_position',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='last_read_chapter',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='scroll_position',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='story',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='readingprogress',
            name='user',
        ),
    ]
