# Generated by Django 4.2.13 on 2025-09-16 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0007_remove_readingprogress_unique_progress_per_user_story_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readingprogress',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='char_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='last_read_chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='scroll_position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='story',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.story'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.UniqueConstraint(fields=('user', 'story'), name='unique_progress_per_user_story'),
        ),
    ]
